---
- name: Ensure the temporary directory exists
  file:
    path: "{{ repos_path }}/{{ repo_info.name }}"
    state: directory

- name: Clone/update the repository
  git:
    repo: "{{ repo_info.url }}"
    dest: "{{ repos_path }}/{{ repo_info.name }}"
    clone: yes
    update: yes

- name: Checkout specific version for {{ repo_info.name }}
  command: git checkout {{ repo_info.version }}
  args:
    chdir: "{{ repos_path }}/{{ repo_info.name }}"

- name: Copy role directory to external_roles directory
  synchronize:
    src: "{{ repos_path }}/{{ repo_info.name }}/{{ role.path }}"
    dest: "{{ external_roles_path }}"
    delete: yes
    recursive: yes
  loop: "{{ repo_info.roles }}"
  loop_control:
    loop_var: role
